#!/bin/bash

function usage() {
  echo "$0 [-l] [-f <input_file>] Lens.lns [command]"
  exit 0
}

function do_augtool() {
  input="${1//$'\n'/\n}"
  shift
  commands="$@"
  (augtool --noautoload | grep  -v '(no matches)') << EOF
set /input "$input$NL"
store $LENS /input /parsed
print /augeas//error
set /augeas/context /parsed
$commands
EOF
}

BYLINE=0

while getopts "lf:h" opt; do
  case $opt in
    l)
      BYLINE=1
      ;;
    f)
      INPUTFILE=$OPTARG
      ;;
    h)
      usage
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done

shift $(( OPTIND - 1 ));

NL="\n"
LENS=$1
shift

if [ -z $LENS ]; then
  echo "E: You must provide a lens"
  usage
  exit 1
fi

if [ -z $INPUTFILE ]; then
  COMMANDS=$@
else
  COMMANDS="$(cat $INPUTFILE)"
fi

if [ $BYLINE = 1 ]; then
  while read line; do
    do_augtool "$line" "$COMMANDS"
  done </dev/stdin
else
  INPUT="$(cat /dev/stdin)"
  do_augtool "$INPUT" "$COMMANDS"
fi
