#!/bin/bash
#
# Load a file with a lens
# using Augeas
#

FILE="$1"
LENS="$2"

shift 2

FILE=$(readlink -f $FILE)

[[ -z $LENS || "x$1" = "x-h" || "x$1" = "x--help" ]] \
   && echo "Usage: $0 <file> <lens> [<cmd>[\n<cmd>]*]" \
   && exit 1

cat <<EOF | augtool --noautoload -i
set /augeas/load/$LENS/lens "$LENS.lns"
set /augeas/load/$LENS/incl "$FILE"
load
$(echo -e $@)
EOF
