#!/bin/sh

FILE="$1"

if [ -z $FILE ]; then
  echo "Usage: $0 <FILE>"
  exit 1
fi

augtool -L -i <<EOF
rm /augeas/load/*["$FILE"!~glob(incl) or "$FILE"=~glob(excl)]
load
set /augeas/context /files$FILE
EOF
