#!/bin/bash
#
# Prints a diff between expected and actual trees when they fail to match

while getopts "ctI:" opt; do
  case $opt in
    c)
      COLORIZE=yes
      shift
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done

TEMP=$(mktemp -d)
trap "rm -rf $TEMP" EXIT

augparse "$@" >$TEMP/output
RET=$?

if egrep -q "^\s*Expected:" $TEMP/output && \
  egrep -q "^\s*Actual:" $TEMP/output; then
    awk '
      /^\s*Expected:/ { exit }
      output == 1 { print }
    ' $TEMP/output > $TEMP/head

    awk '
      /^\s*Actual:/ { exit }
      output == 1 { print }
      /^\s*Expected:/ { output = 1 }
    ' $TEMP/output > $TEMP/expected

    awk '
      /^Syntax error:/ { exit }
      output == 1 { print }
      /^\s*Actual:/ { output = 1 }
    ' $TEMP/output > $TEMP/actual

    (cd $TEMP && diff -u {expected,actual} > $TEMP/diff)
    cat $TEMP/head
    if [ $COLORIZE = "yes" ]; then
      cat $TEMP/diff | colordiff
    else
      cat $TEMP/diff
    fi
else
    cat $TEMP/output
fi

exit $RET
