#!/bin/bash
#
# Prints a diff between expected and actual trees when they fail to match

while getopts "c" opt; do
  case $opt in
    c)
      COLORIZE=yes
      shift
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done

TEMP=$(mktemp -d)
trap "rm -rf $TEMP" EXIT

augparse "$@" >$TEMP/output
RET=$?

if egrep -q "^\s*Expected:" $TEMP/output && \
  egrep -q "^\s*Actual:" $TEMP/output; then
    awk '
      /^\s*Actual:/ { exit }
      output == 1 { print }
      /^\s*Expected:/ { output = 1 }
    ' $TEMP/output > $TEMP/expected

    awk '
      /^Syntax error:/ { exit }
      output == 1 { print }
      /^\s*Actual:/ { output = 1 }
    ' $TEMP/output > $TEMP/actual

    if [ $COLORIZE = "yes" ]; then
      (cd $TEMP && diff -u {expected,actual}| colordiff)
    else
      (cd $TEMP && diff -u {expected,actual})
    fi
else
    cat $TEMP/output
fi

exit $RET
